###
GET http://localhost:3000

###
GET http://localhost:3000/users/1


### Create a new question
POST http://localhost:3000/question/create
Content-Type: application/json

{
  "text": "What is the capital of France?",
  "options": ["Paris", "London", "Berlin", "Rome"],
  "answer": "Paris",
  "category": "General"
}

###

### Read all questions
GET http://localhost:3000/question/read

###

### Read a specific question by ID
GET http://localhost:3000/question/read/1

###

### Update a question
POST http://localhost:3000/question/update
Content-Type: application/json

{
  "id": 1,
  "text": "Updated: What is the capital of Germany?",
  "options": ["Paris", "London", "Berlin", "Rome"],
  "answer": "Berlin",
  "category": "General"
}

###

### Delete a question
POST http://localhost:3000/question/delete/
Content-Type: application/json

{
  "id": 1
}
